# Automatically creates a release when a semantic version tag (X.Y.Z) is pushed

name: "tagged-release"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  call-build:
    uses: ./.github/workflows/gradle.yml

  release:
    needs: call-build

    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sjpp.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: sjpp.jar
