---
name: "tagged-release"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  call-build:
    name: "Call build"
    runs-on: "ubuntu-latest"

    steps:
      - name: build
        uses: .github/workflows/gradle.yml