---
name: "tagged-release"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  call-build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: ./.github/workflows/gradle.yml

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            sjpp/build/libs/sjpp.jar