---
name: "tagged-release"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  call-build:
    name: "Call build"
    runs-on: "ubuntu-latest"

    steps:
      - steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'

      - name: build
        uses: .github/workflows/gradle.yml